### general routes 

#### login

Post http://localhost:5000/login
Content-Type: application/json

{
    "email": "teacher@gmail.com",
    "password": 1234
}

### student routes

####register

Post http://localhost:5000/student/register
Content-Type: application/json

{
    "fullName": "student",
    "email": "student@gmail.com",
    "password": "1234",
    "className": "moshe"
}

### get grades

Get http://localhost:5000/student/grades


### teacher routes

### register

Post http://localhost:5000/teacher/register
Content-Type: application/json

{
    "fullName": "teacher",
    "email": "teacher@gmail.com",
    "password": "1234",
    "className": "moshe"
}

### Add student grade

Post http://localhost:5000/teacher/grade/670e01073e9851d15b299e75
Content-Type: application/json

{

    "note": "good",
    "grade": 5
}


### get student grades

Get http://localhost:5000/teacher/grade/670e01073e9851d15b299e75


### update student grade

Put http://localhost:5000/teacher/grade/670e01073e9851d15b299e75
Content-Type: application/json

{
    "_id":"670e04045f51ac8f14e18b0d",
    "note": "good",
    "grade": 55
}

### get all students

Get http://localhost:5000/teacher/getAllStudents


### get students average grade

Get http://localhost:5000/teacher/StudentsAvg